name: Sample Orca Secrets Scan Workflow

# Trigger the workflow on push and pull requests
on: [push, pull_request]

jobs:
  orca-secrets-scan:
    name: Orca secrets Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       

      - name: Set PROJECT_KEY
        run: echo "PROJECT_KEY=${{ secrets.PROJECT_KEY }}" >> $GITHUB_ENV

      - name: Run Orca Secrets Scan
        uses: orcasecurity/shiftleft-secrets-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ secrets.ORCA_PROJECT_KEY }}
